support for parallel by preloading data
jorainer/ensembldb pull request #150
Opened 2023-11-15 19:39 UTC by Tim-Yu

Hi,

Related to issue #149 

> is there a particular reason to use a `CompressedGRangesList` instead of a standard `GRAngesList`?

Yes, there are two reasons: 1) to ensure that the data is from cdsBy() etc.; 2) for more memory efficiency.

I have updated the remaining coordinate mapping functions to support parallel process calls, along with the corresponding unit tests. 

Additionally, I noticed a minor typo in 2db48b6f28a6526916decfa07145484b6659d1ed and a function error in e5f41605b630a47fad601ce41b4b5edf16d84e8b. 

Best,

Boyu

2023-11-17 12:33 UTC, jorainer requested changes
Thanks for the (quite extensive) contribution! Please address the two small requests to ensure the unit tests run through. And then please also add yourself as an author to the DESCRIPTION.

2023-11-17 12:33 UTC, jorainer commented on R/proteinToX.R
> +setGeneric("proteinToTranscript", signature="db",
Please make sure to also document the `...`

2023-11-17 12:33 UTC, jorainer commented on R/genomeToX.R
> +#' }, mc.preschedule = T, mc.cores = detectCores() - 1)
Please use `TRUE` instead of `T`.

2023-11-18 12:53 UTC, Tim-Yu commented on R/genomeToX.R
> +#' }, mc.preschedule = T, mc.cores = detectCores() - 1)
I changed to parLappy for passing the windows check

2023-11-20 07:36 UTC, jorainer approved these changes
Thanks @Tim-Yu ! I'll merge now and push to BioC.

2023-11-20 07:36 UTC, merged